FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# OCCS rolling updates with REST

Does a rolling update to OCCS deployment. This is a Docker itself that runs on a
worked node in OCCS.

## Redeploy [/]

### Redeploy [POST]

Does a rolling update to OCCS deployment identified by deployment <i>name</i> and redeploys
all nodes matching to <i>filter</i>. When filter is empty matches <i>all</i> nodes.
Deployment name needs to be <i>fully qualified</i>. Filter can be <i>partial</i>. 

When <i>backendName</i> is given tries to disable the node from the HAproxy backend
pool before rolling. After rolling the backend is automatically returned to the pool.

Client is authenticated by the <i>token</i> when it connects to OCCS admin
identified by the given <i>host ip</i>.

+ Request (application/json)

        {
            "token": "security-token",
            "host": "ip",
            "deployment": "name",
            "backendname": "name",
            "filter": "filter"
        }

+ Response 200 (application/json)

    + Headers

            Location: /

    + Body

            {
                "result": "All recycled."
            }